insert into shop (key) values (0);	
update shop set imagename = "shop0.png" where key=0;
update shop set name = "张博士茗茶馆" where key=0;
update shop set address = "芳甸路300号B区405单元" where key=0;
update shop set altitude = "31.226735" where key=0;
update shop set longitude  = "121.557585" where key=0;
update shop set description = "装修凸显中式特色,店面虽不大,却有小桥曲水,小鱼和龟儿在水中散游,非常雅致,店中央摆有古琴,偶有乐师弹奏.这家茶馆主打普洱茶,虽也有铁观音等别的茶种,服务也很到位,入座便有几碟瓜子小食赠送,点了茶之后,服务员小姐会为客人泡茶,不用自己动手.还支持无线上网,也有面,饭等点心供应.点一壶茶,上上网,消磨一个下午的时间,一点儿也不难." where key=0;
update shop set telephone = "021-61017517" where key=0;
update shop set discountInfo = "刷卡消费享受9.5折优惠（烟、酒除外，不与其他优惠同时享受）" where key=0;
update shop set cardType = "金卡" where key=0;	
	
insert into shop (key) values (1);	
update shop set imagename = "shop1.png" where key=1;
update shop set name = "圆苑酒家" where key=1;
update shop set address = "静安区南京西路1038号梅龙镇广场4楼" where key=1;
update shop set altitude = "31.228628" where key=1;
update shop set longitude  = "121.456729" where key=1;
update shop set description = "圆苑酒家以经营地道上海菜和经典粤菜为特色，承蒙各界人士爱戴被冠以“沪上红烧第一家”之称。特别是由本店烧制而成的 “ 红烧肉 ”， 油而不腻，酥而不烂，广受宾客青睐。圆苑酒家目前在上海有6家分店，北京1家分店。餐厅装潢典雅，充满低调奢华的老上海风情，温馨专业的服务，精心制作的美食，让在享受“食”之精彩的同时体会中华美食之神韵。" where key = 1;
update shop set telephone = "021-62726972" where key = 1;
update shop set discountInfo  = "刷卡消费享受8.8折优惠" where key =1;
update shop set cardType = "普卡金卡白金卡" where key = 1;
		
insert into shop (key) values (2);	
update shop set imagename = "shop2.png" where key=2;
update shop set name = "忆品法式铁板烧" where key =2;
update shop set address = "闵行区沪青平公路395号" where key=2;
update shop set altitude= "31.229421" where key=2;
update shop set longitude  = "121.456314" where key=2;
update shop set description = "环境很优雅，有点象咖啡厅呵呵！口味真的很不错，尤其是菲力牛排，很嫩的！" where key=2;
update shop set telephone = "021-54492566" where key=2;
update shop set discountInfo  = "刷卡消费套餐享受9折优惠" where key =2;
update shop set cardType = "普卡金卡白金卡" where key=2;

insert into shop (key) values (3);	
update shop set imagename = "shop3.png" where key=3;
update shop set name = "本杰比印度料理" where key=3;
update shop set address = "浦东新区芳甸路199弄43号" where key=3;
update shop set altitude	= "31.176888" where key=3;
update shop set longitude  = "121.34557" where key=3;
update shop set description = "到处是漂亮而又经典的印度式建筑和在街头随处能见到的印度后裔——德班，南非的一个城市，又称‘印度城’，在那里吃过的咖喱，当然是正宗而又美味的。对我来讲，咖喱是印度的文化之一。听说本杰比的老板和大厨都来自于印度，怀着对咖喱的特有情结，去那里大快朵颐了一次——很可口，喜欢闻那股masala的味道，可是口味有点迎合了我们当地人的口味.有点遗憾。菜可以单点，也有自助的选择，薄饼和咖喱是万万不能错过的" where key=3;
update shop set telephone = "021-50332642" where key=3;
update shop set discountInfo  = "刷交通银行卡消费享受9折优惠(酒水,套餐除外)，不与其他优惠同时享受" where key=3;
update shop set cardType = "普卡金卡白金卡" where key=3;
